MovieApp.WebMVC/Models/Exhibition.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.WebMVC.Models
{
    public class Exhibition
    {
        public int id { get; set; }
        public decimal price { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public DateTime date { get; set; }
        public string image { get; set; }
        
    }
}

MovieApp.WebMVC/Areas/Admin/Controllers/ExhibitionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieApp.WebMVC.Areas.Admin.Models;
using MovieApp.WebMVC.Models;

namespace MovieApp.WebMVC.Areas.Admin.Controllers
{
    public class ExhibitionController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;

        public ExhibitionController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        
        [Authorize]
        public IActionResult Index()
        {
            var isAdmin = Convert.ToBoolean(HttpContext.User.Claims.FirstOrDefault(k => k.Type == ClaimTypes.Role).Value);

            if (!isAdmin) { RedirectToAction("NotAuthorize"); }

            var exhibitions = ExhibitionRepository.getExhibitions();
            return View(exhibitions);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ExhibitionModel model = new ExhibitionModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ExhibitionModel model, IFormFile Picture)
        {
            int thisID = ExhibitionRepository.generateId();
            Exhibition exhibition = new Exhibition
            {
                id = thisID,
                name = model.name,
                price = model.price,
                description = model.description,
                date = model.date,
                image = thisID + ".jpg"
            };
            ExhibitionRepository.AddExhibition(exhibition);

            if (Picture == null || Picture.Length == 0)
                return Content("file not selected");

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot\\img",
                        exhibition.image);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await Picture.CopyToAsync(stream);
            }

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            ExhibitionRepository.Delete(id);
            return View();
        }

        public IActionResult NotAuthorize()
        {
            return View();
        }
    }
}

MovieApp.WebMVC/Areas/Admin/Views/Exhibition/Create.cshtml
@model MovieApp.WebMVC.Areas.Admin.Models.ExhibitionModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12">
    <div class="panel panel-info ">
        <h3>Create Exhibition</h3>
        <div class="panel-body">
            <form asp-area="Admin" asp-controller="Product" asp-action="create" enctype="multipart/form-data" method="post" class="form-horizontal">
                <div class="form-group">
                    <label asp-for="@Model.name" class="control-label"> Name:</label>
                    <input name="name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.price" class="control-label"> Price:</label>
                    <input name="price" type="number" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.description" class="control-label">Description:</label>
                    <input name="description" type="text" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.date" class="control-label">Date (yyyy,mm,dd):</label>
                    <input name="date" type="datetime" class="form-control" />
                </div>
                <div class="form-group">
                    <p>Image</p>
                    <input type="file" name="picture" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-secondary">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

MovieApp.WebMVC/Areas/Admin/Views/Exhibition/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>Deleted</p>

MovieApp.WebMVC/Areas/Admin/Views/Exhibition/Index.cshtml
@model List<MovieApp.WebMVC.Models.Exhibition>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<button type="button" class="btn btn-info" onclick="javascript: window.location.href='@Url.Action("Create", "Exhibition", new { Area ="Admin"})'">+ ADD</button>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Exhibition Image</th>
            <th scope="col">Exhibition Name</th>
            <th scope="col">Exhibition Date</th>
            <th scope="col">Ticket Price</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var exhibition in Model)
        {
            <tr>
                <td>@exhibition.id</td>
                <td>@exhibition.image<img src="~/img/@exhibition.image" style="width:100px;" /></td>
                <td>@exhibition.name</td>
                <td>@exhibition.date</td>
                <td>
                    @exhibition.price
                </td>
                <td>
                    <a href="\Admin\Exhibition\Delete\@exhibition.id"><button type="button" class="btn btn-sm btn-outline-secondary" >Delete</button></a>
                </td>
            </tr>
        }
    </tbody>
</table>

MovieApp.WebMVC/Areas/Admin/Views/Exhibition/NotAuthorize.cshtml
@{
    ViewData["Title"] = "NotAuthorize";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>NotAuthorize</h2>